In [4]:
import sys
import numpy as np

## Basic Numpy Arrays

In [5]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [6]:
a = np.array([1, 2, 3, 4])

In [7]:
b = np.array([8, .5, 1, 1.5, 2])

In [8]:
a[0], a[1]

(1, 2)

In [9]:
a[0:]

array([1, 2, 3, 4])

In [10]:
b[3:]

array([1.5, 2. ])

In [11]:
b[0], b[2], b[-4]

(8.0, 1.0, 0.5)

In [12]:
a([1, 2, 3, 4], dtype=int64)

NameError: name 'int64' is not defined

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [ ]:
A.shape

In [ ]:
A.ndim

In [ ]:
A.size

In [ ]:
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [6, 7, 8],
        [3, 2, 9]
    ]
])

In [13]:
B

NameError: name 'B' is not defined

In [ ]:
B.shape

In [14]:
B.ndim

NameError: name 'B' is not defined

In [15]:
B.size

NameError: name 'B' is not defined

In [ ]:
B.dtype

In [16]:
A

NameError: name 'A' is not defined

In [17]:
A[1]

NameError: name 'A' is not defined

In [18]:
A[1][2]

NameError: name 'A' is not defined

In [19]:
A

NameError: name 'A' is not defined

In [20]:
A[1:,1:]

NameError: name 'A' is not defined

In [21]:
A

NameError: name 'A' is not defined

In [22]:
A[1] = np.array([20, 20, 26])

NameError: name 'A' is not defined

In [23]:
A

NameError: name 'A' is not defined

In [24]:
A[2] = np.array([8, 7, 3])

NameError: name 'A' is not defined

In [25]:
A

NameError: name 'A' is not defined

In [26]:
A.sum()

NameError: name 'A' is not defined

In [27]:
A[1].sum()

NameError: name 'A' is not defined

In [28]:
A.mean()

NameError: name 'A' is not defined

In [29]:
A.std()

NameError: name 'A' is not defined

In [30]:
A.sum(axis=1)

NameError: name 'A' is not defined

In [31]:
A

NameError: name 'A' is not defined

In [32]:
A.mean(axis=0)

NameError: name 'A' is not defined

In [33]:
A.mean(axis=1)

NameError: name 'A' is not defined

In [34]:
A.std(axis=0)

NameError: name 'A' is not defined

In [35]:
A.std(axis=1)

NameError: name 'A' is not defined

In [36]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

In [37]:
print(A[:,:2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


## Broadcasting and Vectorized operations

In [38]:
a = np.arange(9)

In [39]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [40]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [41]:
a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [42]:
a * 10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [43]:
a += 10

In [44]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [45]:
l = [0, 1, 2, 3]

In [46]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [47]:
a = np.arange(5)

In [48]:
a + 20

array([20, 21, 22, 23, 24])

## Boolean Arrays
#### (Also called masks)

In [49]:
a = np.arange(4)

In [50]:
a

array([0, 1, 2, 3])

In [51]:
a[[0,-1]]

array([0, 3])

In [52]:
a[[True, False, True, True]]

array([0, 2, 3])

In [53]:
a

array([0, 1, 2, 3])

In [54]:
a >= 2

array([False, False,  True,  True])

In [55]:
a[a >= 2]

array([2, 3])

In [56]:
a[a >= a.mean()]

array([2, 3])

In [57]:
a[~(a > a.mean())]

array([0, 1])

In [58]:
a[(a == 0) | (a == 1)]


array([0, 1])

In [59]:
A = np.random.randint(100, size=(5,5))

In [60]:
A[:,3:]

array([[25, 85],
       [98, 16],
       [79, 37],
       [27, 56],
       [16, 39]])

In [61]:
A > 50

array([[False,  True, False, False,  True],
       [False,  True,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False,  True, False,  True],
       [False,  True,  True, False, False]])

In [69]:
B = np.random.randint(999, size=(20,20))

In [85]:
B[:5,8:]

array([[760, 897, 116, 213,  23,  40, 183, 802, 951, 345, 236, 804],
       [992, 953, 310, 933, 751, 374, 921, 276, 977, 989, 993, 436],
       [563, 482, 945,  14, 543, 964, 597, 242, 880, 957, 126, 233],
       [277, 550, 294, 292, 427, 737, 935, 827, 749, 496, 949, 170],
       [745, 478, 772, 394, 450,  18, 340, 572, 371, 197, 186, 451]])

In [91]:
B

array([[315, 224, 622, 656, 391, 236, 578, 321, 760, 897, 116, 213,  23,
         40, 183, 802, 951, 345, 236, 804],
       [ 51, 766, 694, 615, 694, 442, 975, 815, 992, 953, 310, 933, 751,
        374, 921, 276, 977, 989, 993, 436],
       [503, 872, 585,   7, 128, 510, 506, 928, 563, 482, 945,  14, 543,
        964, 597, 242, 880, 957, 126, 233],
       [ 23, 190, 742, 861, 562, 997, 259, 973, 277, 550, 294, 292, 427,
        737, 935, 827, 749, 496, 949, 170],
       [874, 611, 612, 832,  68, 754, 829, 296, 745, 478, 772, 394, 450,
         18, 340, 572, 371, 197, 186, 451],
       [  3, 542, 806, 301, 549, 912, 311, 880, 426,  10, 442, 358, 905,
        453, 694, 886,   1, 950, 519, 260],
       [683, 335, 375, 908, 687, 926,  73, 757, 503, 313, 184, 202, 134,
        205, 191, 737, 524, 813, 196, 844],
       [ 52, 250,  80, 357, 854, 889, 193, 613, 860, 216, 547,  46, 165,
        728, 614,  58, 820,   7, 183, 789],
       [161, 777, 665,  73, 998, 743, 565, 720, 265, 630, 146, 2

In [103]:
r = np.random.randint(20, size=(9,9))

In [110]:
r

array([[ 1, 16, 12,  0,  4, 12,  3,  5, 10],
       [ 5,  4, 10,  8, 18,  8,  0,  0,  1],
       [ 8, 15, 13, 13,  3,  9, 14,  8,  0],
       [10,  7, 12,  1,  6, 12, 16,  1,  0],
       [16,  2,  5, 13, 18,  4,  7, 13,  8],
       [14, 13,  2, 16, 11, 15, 12,  1, 12],
       [15, 12,  9,  4, 19, 16,  2, 18,  5],
       [10, 13,  9, 19,  8,  1, 19,  1, 12],
       [ 3,  9, 14,  5,  3, 13, 17, 15,  4]])

In [121]:
r.max()

19

In [64]:
a = np.arange(5)

In [65]:
a

array([0, 1, 2, 3, 4])

In [66]:
print(a <= 3)

[ True  True  True  True False]


### Linear Algebra

In [123]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [124]:
B = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])

In [128]:
A.dot(B)

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [129]:
A @ B

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100]])

In [130]:
B.T

array([[1, 3, 5],
       [2, 4, 6]])

In [133]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Size of objects in Memory
#### Int, Floats

In [142]:
# An integer in Python is > 24 bytes
sys.getsizeof(1)

28

In [ ]:
# Longs are even larger
sys.getsizeof(10**100)

In [ ]:
# Numpy size is much smaller
np.dtype(int).itemsize

In [ ]:
np.dtype(float).itemsize

### Lists are even larger

In [ ]:
# A one-element list
sys.getsizeof([1])

In [ ]:
# An Array of one element in numpy
np.array([1]).bytes

### And performance is also important

In [ ]:
l = list(range(100000))

In [ ]:
a = np.arange(10000)

In [ ]:
%time np.sum(a ** 2)

In [ ]:
%time sum([x == 2 for x in l])

### Useful Numpy functions

#### random

In [ ]:
np.random.random(size=2)

In [ ]:
np.random.normal(size=2)

In [ ]:
np.random.rand(2, 4)

#### arange

In [ ]:
np.arange(10)

In [ ]:
np.arange(5, 10)

In [ ]:
np.arange(0, 1, .1)

#### reshape

In [ ]:
np.arange(10).reshape(2,5)

In [ ]:
np.arange(10).reshape(5,2)

#### linspace

In [ ]:
np.linspace(0, 1, 5)

In [ ]:
np.linspace(0, 1, 20)

In [ ]:
np.linspace(0, 1, 20, False)

#### zeros, ones, empty

In [ ]:
np.zeros(5)

In [ ]:
np.zeros((3, 3))

In [ ]:
np.zeros((3,3), dtype=np.int)

In [ ]:
np.ones(5)

In [ ]:
np.ones((3, 3))

In [ ]:
np.empty(5)

In [ ]:
np.empty((2, 2))

#### identity and eye

In [ ]:
np.identity(3)

In [ ]:
np.eye(3, 3)

In [ ]:
np.eye(8,4, k=1)

In [ ]:
np.eye(8, 4, k=-3)

In [ ]:
"Hello World"[6]